apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-server-1
  name: web-server-1
spec:  
  replicas: 3
  selector:
    matchLabels:
      app: web-server-1
  strategy: {}
  template:
    metadata:
      labels:
        app: web-server-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - prod
                      - dev
                  - key: application
                    operator: NotIn
                    values:
                      - app1
      containers:
      - image: chmadhus/web-server-1:delhi
        name: web-server-1