apiVersion: v1
kind: Service
metadata:
  labels:
    app: bangalore-deploy
  name: bangalore-deploy
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: bangalore-deploy
status:
  loadBalancer: {}
