apiVersion: v1
kind: Service
metadata:
  labels:
    app: delhi-deploy
  name: delhi-deploy
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: delhi-deploy
status:
  loadBalancer: {}