apiVersion: v1
kind: Service
metadata:
  name: madhu-svc
spec:
  type: ExternalName
  externalName: www.ch-ms.co.in #Any DNS server name
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
   - port: 443
     name: htts
     targetPort: 443
     protocol: TCP