apiVersion: v1
kind: Service
metadata:
  labels:
    run: headless-1
  name: headless-1
spec:
  clusterIP: None
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: headless-1