apiVersion: v1
kind: Service
metadata:
  labels:
    app: pod1
  name: pod1
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: pod1
  type: NodePort