apiVersion: v1
kind: Service
metadata:
  name: pgsql
spec:
  clusterIP: None
  selector:
    app: pgsql
  ports:
    - name: pgsql
      protocol: TCP
      port: 5432
      targetPort: 5432
---
kind: Endpoints
apiVersion: v1
metadata:
  name: pgsql
subsets:
  - addresses:
      - ip: 44.168.1.3
    ports:
      - port: 5432
        name: pgsql