apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: delhi-allow-pod
  namespace: delhi
spec:
  podSelector:
    matchLabels:
      app: delhinginx01
  ingress:
  - from:
      - podSelector:
          matchLabels:
            ns: delhi