apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multiplecontainers
  name: multiplecontainers
spec:
  containers:
  - image: redis
    name: pod1
  - image: chmadhus/web-server-2:hyderabad
    name: pod2
  restartPolicy: Always