apiVersion: batch/v1
kind: CronJob
metadata:
  name: deamonkiller-cron
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "Hello deamonkillerM!!"]
          restartPolicy: Never