apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  completions: 2
  parallelism: 2
  template:
    metadata: 
    spec:
      containers:
      - image: busybox
        command: ["echo", "hello world"]
        name: test-job
      restartPolicy: Never
